
name: Env Injection Test
on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Env var to inject'
        required: false
        default: 'SAFE'

jobs:
  print-env:
    runs-on: ubuntu-latest
    steps:
      - name: Print Env
        run: env
      - name: Check Context
        run: echo "${{ toJson(env) }}"
      - name: Unsafe Echo
        run: echo "Input: ${{ github.event.inputs.target_env }}"
