name: Env Injection Test
on:
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Env var to inject'
        required: false
        default: 'SAFE'

jobs:
  print-env:
    runs-on: ubuntu-latest
    steps:
      - name: Unsafe Echo
        run: echo "Input: ${{ github.event.inputs.target_env }}"
      - name: ÐŸROOF OF SUCCESS (Post-Check)
        run: |
          echo "Malicious Env Var: $PWNED"
          if [[ "$PWNED" == "success" ]]; then
            echo "[+] VUMNERABILITY CONFIRMED"
          fi
